### ISSUE TITLE
Update btcd OP_CCV implementation argument order and tweak

### ISSUE THREAD

**Issue by dgpv** [halseth/mattlab#1]
Hello

I've decided to implement `CHECKCONTRACTVERIFY` plugin for B'SST (https://github.com/dgpv/bsst): https://gist.github.com/dgpv/8e8e8f5fe12a9fae3133da9bd172c925

I used https://github.com/Merkleize/bitcoin/tree/checkcontractverify as a reference for `CHECKCONTRACTVERIFY`

The problem I hit when I tried to test this plugin on the "answerScript" from `scripts/script.go` is that it seems to assume different order of arguments for `CHECKCONTRACTVERIFY` than it is in the repo linked above (for example, the `index` is at `-2` on the stack while in the repo above it is at `-4`).

Can I have a link to the repo with relevant implementation ?

What is the most recent implementation for `CHECKCONTRACTVERIFY` ?

Note: my motivation was simply to look at how easy new complex opcodes can be added to B'SST, not that I have any preference for this or that covenant-related opcode. `CHECKCONTRACTVERIFY` was simply interesting because it has plenty of rules it imposes on its arguments, and this repo has some scripts that use the opcode, that I can use to test the plugin

**Comment by halseth** [comment]
That's correct, the implementation this repo is based on, is a little bit out of date and the arguments aren't in the same order as the one you are looking at (and yes, that's the correct one!).

I will try to update the implementation and scripts here to be compatible with https://github.com/Merkleize/bitcoin/tree/checkcontractverify . Thanks for the heads up!

**Comment by halseth** [comment]
It can also be worth mentioning that the btcd implemantion currently uses a tagged hash for the  data tweak, which should be changed to an untagged hash as in the reference implementation.

**Comment by halseth** [comment]
Hi @dgpv The scripts should now be aligned with the reference implementation.

**Comment by dgpv** [comment]
Great, I've tested and updated the plugin, thanks.
